services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kd2-backend
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
      service-obs:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kd2-frontend
    ports:
      - "4173:4173"
    env_file:
      - .env

  service-db:
    image: postgres:14.7-alpine
    container_name: kd2-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: kd2-pgadmin4
    image: dpage/pgadmin4:7
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - service-db

  service-obs:
    image: chrislusf/seaweedfs:latest
    container_name: kd2-seaweedfs
    env_file:
      - .env
    ports:
      - "8333:8333"
      - "9333:9333"
    volumes:
      - obs-data:/data
    restart: unless-stopped
    command:
      - server
      - -dir=/data
      - -s3
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://service-obs:8333" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  pgadmin-data:
  obs-data: