package ru.hh.kakdela.v2.exception;

public enum ErrorCode {

  // Responses and answers

  NOT_ALL_MANDATORY_QUESTIONS_ANSWERED,
  RESPONSE_NOT_FOUND_OR_COMPLETED,
  RESPONSE_BRANCH_CLOSED,
  ANSWER_NOT_FOUND,

  // Surveys

  SURVEY_IS_EMPTY,

  // Pages

  SURVEY_PAGE_NOT_FOUND,

  // Questions

  QUESTION_NOT_FOUND,
  ANSWER_OPTION_NOT_FOUND,

  // Conditions

  CONDITION_NOT_FOUND,
  CONDITIONS_OF_PAGE_HAVE_CONFLICTS,
  CONDITION_NODE_IS_NOT_ATOM,
  CONDITION_FOR_THESE_PAGE_AND_NEXT_PAGE_ALREADY_EXISTS,
  CONDITION_NEXT_PAGE_NOT_FOUND,
  CONDITION_SHOULD_NAVIGATE_FORWARD,
  CONDITION_TREE_IS_EMPTY,
  CONDITION_TREE_IS_NOT_EMPTY,
  CONDITION_TREE_HEIGHT_LIMIT_REACHED,
  CONDITION_NODE_OPERATOR_IS_NOT_LINK,
  CONDITION_NODE_NOT_FOUND,
  CONDITION_LINK_NODES_ONLY_SHOULD_BE_MODIFIED,
  CONDITION_PARENT_NODE_NOT_FOUND,
  CONDITION_CHILD_NODE_NOT_FOUND,

  // Common

  ACCESS_DENIED,
  BAD_CREDENTIALS,
  ACCOUNT_DELETED,
  RESOURCE_NOT_FOUND,
  ENTITY_NOT_FOUND,
  BAD_REQUEST_DATA,
  INTERNAL_SERVER,
  UNDEFINED
}
