package ru.hh.kakdela.v2.exception;

public enum ErrorCode {
  NOT_ALL_MANDATORY_QUESTIONS_ANSWERED,
  ACCESS_DENIED,
  BAD_CREDENTIALS,
  ACCOUNT_DELETED,
  RESOURCE_NOT_FOUND,
  ENTITY_NOT_FOUND,
  BAD_REQUEST_BODY,
  INTERNAL_SERVER,
  UNDEFINED
}
