# Logging configuration
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
# Cors configuration
cors.allowed-origins=http://217.198.168.32:44306,https://217.198.168.32:44306
# Email settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
