# Application configuration
app.jwt.secret=${JWT_SECRET}
app.host=${APP_HOST}
app.port=${APP_PORT}
# 900 секунд = 15 минут
app.tokens.access.max-age=900
# 2592000 секунд = 30 дней
app.tokens.refresh.max-age=2592000
# 604800 секунд = 7 дней
app.tokens.response-access.max-age=604800
app.attachments.url-max-age=60
# Web server configuration
server.port=8080
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/monitor
# DataSource configuration
spring.datasource.url=jdbc:postgresql://service-db:5432/kd2_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Cors configuration
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=*
# Временно пустой
cors.exposed-headers=
cors.allowed-origins=http://${app.host}:${app.port},https://${app.host}:${app.port}
cors.allow-credentials=false
cors.max-age=3600
# Object storage configuration
cloud.aws.internal-endpoint=http://service-obs:8333
cloud.aws.public-endpoint=${app.url}
cloud.aws.region=eu-central-1
cloud.aws.credentials.access-key-id=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-access-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.bucket.name=${S3_BUCKET}
# Async configuration
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=mail-Async-
# Email settings
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
app.mail.from=${MAIL_FROM}
#Oauth2 configuration
app.oauth2.hh-user-agent=kakdela/1.0 (support@kakdela.ru)
spring.security.oauth2.client.registration.hh.client-id=${HH_CLIENT_ID}
spring.security.oauth2.client.registration.hh.client-secret=${HH_CLIENT_SECRET}
spring.security.oauth2.client.registration.hh.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.hh.redirect-uri={baseUrl}/api/auth/oauth2/callback/{registrationId}
spring.security.oauth2.client.provider.hh.authorization-uri=https://hh.ru/oauth/authorize
spring.security.oauth2.client.provider.hh.token-uri=https://api.hh.ru/token
spring.security.oauth2.client.provider.hh.user-info-uri=https://api.hh.ru/me
spring.security.oauth2.client.provider.hh.user-name-attribute=id