# Application configuration
app.url=https://${app.host}:${app.port}
# Logging configuration
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
# Email settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
# Oauth2 configuration
app.oauth2.frontend-redirect-uri=https://${app.host}:${app.port}/auth/callback
