# Logging configuration
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
# Email settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true