# Application configuration
app.url=http://${app.host}:${app.port}
# Logging configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
# Object storage configuration
cloud.aws.public-endpoint=http://${app.host}:8333
