# Application configuration
app.jwt-secret=${JWT_SECRET}
# Web server configuration
server.port=8080
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
# DataSource configuration
spring.datasource.url=jdbc:postgresql://service-db:5432/kd2_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=false
# ВРЕМЕННО: УДАЛИТЬ, КОГДА БОГДАН ПЕРЕВЕДЁТ ВСЁ НА TRANSACTIONAL
spring.jpa.properties.hibernate.current_session_context_class=thread
# Cors configuration
cors.allowed-origins=http://localhost:4173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=*
cors.exposed-headers=Authorization
cors.allow-credentials=false
cors.max-age=3600
