# Application configuration
app.jwt-secret=${JWT_SECRET}
app.attachments.url-max-age=60
# 900 секунд = 15 минут
app.tokens.access.max-age=900
# 2592000 секунд = 30 дней
app.tokens.refresh.max-age=2592000
# 604800 секунд = 7 дней
app.tokens.response-access.max-age=604800
# Logging configuration
logging.level.org.springframework.security=${SPRING_SECURITY_LOGGING_LEVEL}
logging.level.org.springframework.web=${SPRING_WEB_LOGGING_LEVEL}
# Web server configuration
server.port=8080
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# DataSource configuration
spring.datasource.url=jdbc:postgresql://service-db:5432/kd2_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=false
# Cors configuration
cors.allowed-origins=http://localhost:4173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=*
# Временно пустой
cors.exposed-headers=
cors.allow-credentials=false
cors.max-age=3600
# Object storage configuration
cloud.aws.internal-endpoint=http://service-obs:8333
cloud.aws.public-endpoint=http://localhost:8333
cloud.aws.region=eu-central-1
cloud.aws.credentials.access-key-id=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-access-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.bucket.name=${S3_BUCKET}
