import type { SurveyShortResponse } from '@/pages/Survey/components/SurveyList/types';

export const mockSurveys: SurveyShortResponse[] = [
    {
        id: 'survey-1',
        title: 'Оценка адаптации',
        description: 'Опрос для новых сотрудников',
        isPublished: false,
        createdAt: '2026-06-01T10:00:00Z',
    },
    {
        id: 'survey-2',
        title: 'Командный пульс',
        description: 'Еженедельный опрос настроения команды',
        isPublished: true,
        createdAt: '2026-06-03T12:00:00Z',
    },
    {
        id: 'survey-3',
        title: 'Обратная связь по продукту',
        description: null,
        isPublished: false,
        createdAt: '2026-06-08T09:30:00Z',
    },
    {
        id: 'survey-4',
        title: 'Проверка процессов',
        description: 'Внутренний опрос по рабочим процессам',
        isPublished: true,
        createdAt: '2026-06-09T11:15:00Z',
    },
    {
        id: 'survey-5',
        title: 'Ретроспектива квартала',
        description: 'Сбор обратной связи по итогам квартала',
        isPublished: false,
        createdAt: '2026-06-10T08:45:00Z',
    },
    {
        id: 'survey-6',
        title: 'Оценка обучения',
        description: 'Фидбек по образовательной программе',
        isPublished: true,
        createdAt: '2026-06-10T14:20:00Z',
    },
    {
        id: 'survey-7',
        title: 'Идеи для улучшений',
        description: null,
        isPublished: false,
        createdAt: '2026-06-11T09:00:00Z',
    },
    {
        id: 'survey-8',
        title: 'Пульс руководителей',
        description: 'Короткий опрос для лидов команд',
        isPublished: true,
        createdAt: '2026-06-11T16:30:00Z',
    },
    {
        id: 'survey-9',
        title: 'Качество коммуникации',
        description: 'Опрос о взаимодействии между командами',
        isPublished: false,
        createdAt: '2026-06-12T10:10:00Z',
    },
    {
        id: 'survey-10',
        title: 'Инструменты разработки',
        description: 'Сбор мнений о текущем наборе инструментов',
        isPublished: true,
        createdAt: '2026-06-12T13:40:00Z',
    },
    {
        id: 'survey-11',
        title: 'Планирование задач',
        description: null,
        isPublished: false,
        createdAt: '2026-06-13T07:50:00Z',
    },
    {
        id: 'survey-12',
        title: 'Качество коммуникации',
        description: 'Опрос о взаимодействии между командами',
        isPublished: false,
        createdAt: '2026-06-12T10:10:00Z',
    },
    {
        id: 'survey-13',
        title: 'Инструменты разработки',
        description: 'Сбор мнений о текущем наборе инструментов',
        isPublished: true,
        createdAt: '2026-06-12T13:40:00Z',
    },
    {
        id: 'survey-14',
        title: 'Планирование задач',
        description: null,
        isPublished: false,
        createdAt: '2026-06-13T07:50:00Z',
    },
];
