name: CD
on:
  push:
    branches:
      - main
env:
  dockerhub-repository-name: kakdela.v2
jobs:
  changes:
    name: Determine what has been changed
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Do some magic to find changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - '!frontend/*.md'
            backend:
              - 'backend/**'
              - '!backend/*.md'
              - '!backend/src/main/resources/schema.sql'
          predicate-quantifier: every
  backend-image:
    name: Build and push backend Docker image
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Packages
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image name for GitHub Packages
        run: echo "GHCR_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.dockerhub-repository-name }}:backend-latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.dockerhub-repository-name }}:backend-${{ github.sha }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:backend-latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:backend-${{ github.sha }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
  frontend-image:
    name: Build and push frontend Docker image
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Packages
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image name for GitHub Packages
        run: echo "GHCR_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.dockerhub-repository-name }}:frontend-latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.dockerhub-repository-name }}:frontend-${{ github.sha }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:frontend-latest
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:frontend-${{ github.sha }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend
