name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  changes:
    name: Determine what has been changed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v7
      - name: Do some magic to find changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
  backend-verification:
    name: Run Maven verify phase (tests are temporary excluded)
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v7
      - name: Set up Reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Run Maven verify phase
        run: cd backend && ./mvnw verify -Dmaven.test.skip=true
      - name: Do Checkstyle report with Reviewdog
        run: >
          reviewdog
          -f=checkstyle
          -reporter=github-pr-review
          -fail-level=any
          -diff="git diff" 
          < backend/target/checkstyle-result.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  frontend-verification:
    name: Run Prettier check, ESLint, TypeScript check and build project
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v7
      - name: Set up Reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
      - name: Install yarn and dependencies
        run: >
          cd frontend
          && npm install -g yarn
          && yarn install
        env:
          HUSKY: 0
      - name: Run Prettier check
        run: cd frontend && yarn run format-check
      - name: Run ESLint
        run: cd frontend && yarn run lint -- -f checkstyle -o eslint-results.xml
      - name: Do ESLint report with Reviewdog
        run: >
          reviewdog
          -f=checkstyle
          -reporter=github-pr-review
          -fail-level=any
          -diff="git diff" 
          < frontend/eslint-results.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TypeScript type check and do report with Reviewdog
        run: > 
          cd frontend 
          && yarn run ts-check 
          | reviewdog
          -efm="%f:%l:%c - %m"
          -reporter=github-pr-review
          -fail-level=any
          -diff="git diff"
      - name: Build project
        run: cd frontend && yarn run build
  docker-validation:
    name: Run Docker compose and wait for all containers healthy (or running)
    needs:
      - backend-verification
      - frontend-verification
    if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v7
      - name: Run Docker compose and wait
        run: docker compose -f docker-compose.yml up --build --wait --wait-timeout 180